### ISSUE TITLE
Arguments of `arf_mul_2exp_si`: mutability

### ISSUE THREAD

**Issue by Chris00** [wjyoumans/arb-sys#2]
The header file `arf.h` declares
```C
ARF_INLINE void
arf_mul_2exp_si(arf_t y, const arf_t x, slong e)
```
I therefore do not understand by the [second argument of `arb_sys::arf::arf_mul_2exp_si` is mutable](https://docs.rs/arb-sys/0.2.5/arb_sys/arf/fn.arf_mul_2exp_si.html):
```rust
pub unsafe extern "C" fn arf_mul_2exp_si(
    y: *mut arf_struct, 
    x: *mut arf_struct, 
    e: mp_limb_signed_t
)
```

**Comment by wjyoumans** [comment]
The bindings are auto generated using `rust-bindgen` which for some reason doesn't notice some arguments should be `const` and instead makes them mutable. So far I've been manually correcting them but I plan on asking the bindgen people about it.

Feel free to correct the bindings in `arf.rs` and make a pull request if you would like it fixed right away, otherwise I will get to it when I can.

**Comment by Chris00** [comment]
The same is true for `arf_printd`:
```C
ARF_INLINE void
arf_printd(const arf_t y, slong d)
```
v.s.
```rust 
pub unsafe extern "C" fn arf_printd(
    y: *mut arf_struct, 
    d: mp_limb_signed_t
)
```

**Comment by Chris00** [comment]
> Feel free to correct the bindings in arf.rs and make a pull request 

I will.

**Comment by wjyoumans** [comment]
It seems the issue is known and unresolved at `rust-bindgen`. See the mention above.
